services:
  mysql:
    image: mysql:8
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: UserDB
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - devops-net

  app:
    build: .
    container_name: java-login
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - devops-net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      - mysql
    networks:
      - devops-net

networks:
  devops-net:
    driver: bridge

volumes:
  mysql_data:
